### ISSUE TITLE
テスト基盤のコードレビュー

### ISSUE THREAD

**Issue by yamad07** [ispec-inc/monorepo#24]
**概要**
コードをざっと見ていただき、とくにテスト周りで修正できそうなポイントを[スクラップボックス](https://scrapbox.io/ispec/go-distributed-monolith_%E6%94%B9%E5%96%84%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88_%E3%81%97%E3%82%85%E3%82%82%E3%82%93%E3%81%95%E3%82%93)に列挙してもらう。
りんさんがすでにやってくれているが、レビューの重複とかは問題ないのと、優先順位がたかそうなものがあればその旨も書いていただけると嬉しいです！

**参考**
- [りんさん](https://scrapbox.io/ispec/go-distribution-monolith_%E6%94%B9%E5%96%84%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88_%E3%82%8A%E3%82%93%E3%81%95%E3%82%93)がやってくれているもの

**工数**
- 4

**Comment by shumon84** [comment]
こちら遅くなりましたが、レビューおわりました！
https://scrapbox.io/ispec/go-distributed-monolith_%E6%94%B9%E5%96%84%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88_%E3%81%97%E3%82%85%E3%82%82%E3%82%93%E3%81%95%E3%82%93
