### ISSUE TITLE
toolsパッケージを使ったバージョンの固定 

### ISSUE THREAD

**Issue by yamad07** [ispec-inc/monorepo#26]
## 概要
toolsパッケージを導入してバージョンを固定する(mockgen、realize、lint)
- [参考](https://github.com/go-modules-by-example/index/blob/master/010_tools/README.md)

## 工数
**合計**
3

**コーディング**
2

**ロジック**
1

**キャッチアップ**
0

**Comment by shumon84** [comment]
各ツールのバージョンはいくつにすればいいですか？(全部最新?)

**Comment by shumon84** [comment]
とりあえず、全部upstreamを取ってきましたが、バージョン問題ないですか？
| tool | version |
| ---- |----  |
| goimports  | v0.0.0-20201009162240-fcf82128ed91 |
| golint | v0.0.0-20200302205851-738671d3881b |
| mockgen | v1.4.4 |
| realize | v2.0.2 |
