### ISSUE TITLE
golintからstaticcheckへの移行

### ISSUE THREAD

**Issue by yamad07** [ispec-inc/monorepo#76]
# 何をするのか
goの静的解析ツールをstaticcheckへ移行する

# なぜやるのか
golintが非推奨になった。

# どうやってやるのか
今作っているスタイルガイドのルールのうち、staticcheckで対応できる部分の設定をする。

# 工数
## ロジックの複雑さ
1

## サードパーティ製ツールのキャッチアップコスト
3

## 書くコードの量
2

**Comment by tanimutomo** [comment]
イメージ
- https://blog.cybozu.io/entry/2021/02/26/081013 (参考になりそう)

公式ドキュメント
- https://staticcheck.io/docs/

使い方
- `staticcheck github.com/example/...` こんな感じ
- `staticcheck.conf` (toml) で設定できる．おいた場所以下のディレクトリで設定が有効になる．override可能．
- `inherit, all, -HOGE` などが使える
- option一覧 : https://staticcheck.io/docs/options (checksの一覧 : https://staticcheck.io/docs/checks <- めっちゃある)
- command line args で設定を変更できたり，lineごとに設定を無視できたりする

デフォtルトの設定
```toml
checks = ["all", "-ST1000", "-ST1003", "-ST1016"]
initialisms = ["ACL", "API", "ASCII", "CPU", "CSS", "DNS",
	"EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID",
	"IP", "JSON", "QPS", "RAM", "RPC", "SLA",
	"SMTP", "SQL", "SSH", "TCP", "TLS", "TTL",
	"UDP", "UI", "GID", "UID", "UUID", "URI",
	"URL", "UTF8", "VM", "XML", "XMPP", "XSRF",
	"XSS"]
dot_import_whitelist = []
http_status_code_whitelist = ["200", "400", "404", "500"]
```

**Comment by tanimutomo** [comment]
一旦，defaultの設定のままで，どうなるか試してみようかな
